---
# tasks file for linuxenv

- name: Update and upgrade apt
  ansible.builtin.apt:
    update_cache: true
    upgrade: true
    cache_valid_time: 3600
    become_user: root

- name: Update and upgrade pacman
  community.general.pacman:
    update_cache: true
    upgrade: true
    state: present
    become_user: root
